[package]
name = "dorico-speededitor"
version = "0.1.0"
edition = "2024"

[dependencies]
bmd-speededitor = "0.2.3"
tinyjson = "2.5.1"
tokio = { version = "1.43.0", features = ["full"] }
websockets = "0.3.0"
